server:
  port: 8082
spring: 
  cloud:
    config:
      uri: ${currencyservice.configserverurl}
      fail-fast: false
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: ${currencyservice.zipkinurl}
    
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    metadata-map:
      zone: A
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: ${currencyservice.eurekaurl}
   
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
       
feign:
  hystrix:
    enabled: true

  