server:
  port: 8082
spring:  
  application:
    name: CurrencyExchangeService
  profiles:
    active: dev
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
       
feign:
  hystrix:
    enabled: true

  