spring:
  cloud:
    config:
      uri: ${currencyservice_configserverurl}
      fail-fast: false  
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: ${currencyservice_zipkinurl}
    
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    metadata-map:
      zone: A
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: ${currencyservice_eurekaurl}
   
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
       
feign:
  hystrix:
    enabled: true

logging:
  pattern:
    level: "[%X{X-B3-TraceId} : %X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n"           
       