server:
  port: 8082
spring:  
  application:
    name: CurrencyExchangeService
  profiles:
    active: dev
    
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.99.100:9411/
  
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
       
feign:
  hystrix:
    enabled: true

  