spring:
  cloud:
    config:
      uri: ${currencyservice.configserverurl:http://localhost:8888}
      fail-fast: false  
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.99.100:9411/
    
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    preferIpAddress: true
    metadata-map:
      zone: A
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: ${currencyservice.eurekaurl:http://localhost:8761/eureka}
   
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
       
feign:
  hystrix:
    enabled: true

logging:
  pattern:
    level: "[%X{X-B3-TraceId} : %X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n"           
       